[workspace]
members = [
  "crates/cpu",
  "crates/windows",
  "crates/ui",
  "crates/windows",
  "crates/gbmu",
  "crates/memory",
  "crates/shared",
  "crates/soc",
  "crates/ppu",
  "crates/interrupts"
]
resolver = "2"
