[package]
name = "windows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.7.0"
iced_wgpu = {git = "https://github.com/hecrj/iced"}
iced_winit = {git = "https://github.com/hecrj/iced"}
ui = { path = "../ui" }
soc = { path = "../soc" }
