[package]
name = "windows"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.24.0"
iced_glutin = "0.2"
glow = "0.6"
gui = { path = "../gui"}
