[package]
name = "apu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.3"
shared = { path = "../shared" }
blip_buf = "0.1.3"
cpal = "0.13.4"