mod alu_8bits;
mod loads_16bits;
mod loads_8bits;
mod miscellaneous;
mod rotates_shifts;
mod bit_operations;
mod jumps;
mod calls;
mod returns;
mod restart;

pub use alu_8bits::*;
pub use loads_16bits::*;
pub use loads_8bits::*;
pub use miscellaneous::*;
pub use rotates_shifts::*;
pub use bit_operations::*;
pub use jumps::*;
pub use calls::*;
pub use returns::*;
pub use restart::*;